### ISSUE TITLE
Chat channel?

### ISSUE THREAD

**Issue by anithri** [SpencerCDixon/redux-cli#113]
It's be nice to have a place to have discussion and bat ideas around in real time.  Giiter, IRC, Slack...?

Anyone else interested?

**Comment by jamesr73** [comment]
Would be useful to round out the 2.0 feature set. No pref which option to use. I'm in GMT.

**Comment by anithri** [comment]
[![Gitter Chat Channel](https://img.shields.io/gitter/room/nwjs/nw.js.svg)](https://gitter.im/redux-cli/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
