### ISSUE TITLE
eslint quotes avoidEscape

### ISSUE THREAD

**Issue by jamesr73** [SpencerCDixon/redux-cli#119]
Any objection to tweaking the eslint rules to allow double quotes to be used when there is a single quote in the string?

```
"quotes": [2, "single", {"avoidEscape": true}],
```

This would make life [prettier](https://github.com/prettier/prettier)

**Comment by jamesr73** [comment]
This change is currently in #110 😜

**Comment by anithri** [comment]
Accepted as part of #110
