### ISSUE TITLE
Look for .reduxrc in ~ if there is none in the projects directory allowing for users to create just one .reduxrc that could potentially work across projects

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/redux-cli#12]

**Comment by ericwooley** [comment]
Maybe just search up the file tree and use the first one you find?

**Comment by anithri** [comment]
2.0 is going implement [rc](https://github.com/dominictarr/rc) to read .reduxrc` 

This will allow much more freedom in placing those file.  Locations can be...
Given your application name (`appname`), rc will look in all the obvious places for configuration.

* command line arguments (parsed by minimist)
* environment variables prefixed with `redux_`
* or use "\_\_" to indicate nested properties <br/> _(e.g. `appname_foo__bar__baz` => `foo.bar.baz`)_
* if you passed an option `--config file` then from that file
* a local `.reduxrc` or the first found looking in `./ ../ ../../ ../../../` etc.
* `$HOME/.reduxrc`
* `$HOME/.redux/config`
* `$HOME/.config/redux`
* `$HOME/.config/redux/config`
* `/etc/reduxrc`
* `/etc/redux/config`
* the defaults object you passed in.

**Comment by ericwooley** [comment]
I have been using this @SpencerCDixon @anithri for a bit now, and it has been working out pretty well. Maybe it can save you some work.

https://github.com/ericwooley/thewooleyway/tree/master/packages/up-resolve

**Comment by anithri** [comment]
Addressed by #100
