### ISSUE TITLE
Make component case configurable

### ISSUE THREAD

**Issue by ericwooley** [SpencerCDixon/redux-cli#16]
I develop with a team on a Mac and deploy on a Linux machine. Mac is not case sensitive, so having case sensitive file names leads to undiscovered import errors until it is deployed.

**Comment by SpencerCDixon** [comment]
Definitely open to a PR!  Otherwise I can get around to this when I have some free time

**Comment by SpencerCDixon** [comment]
@ericwooley you can now use a `fileCasing` arg and it will generate file names in either snake, pascal, or camel case.  Hope that helps!  Need to upgrade to 1.1 to use

**Comment by ericwooley** [comment]
Nice! that was lickity split! Much appreciated, I was just about to start a PR

**Comment by SpencerCDixon** [comment]
:+1: np.  Had some free time and figured it is a pretty valuable setting
