### ISSUE TITLE
Error code: 128

### ISSUE THREAD

**Issue by d0nkeyBOB** [SpencerCDixon/redux-cli#21]
On a new project creation, I'm getting an error 128 within the setup when it tries to pull from the starter-kit repo. 

I believe it fails within function 'pullDownKit()' of /src/cli/redux-new.js.

`const pull = exec('git pull https://github.com/davezuko/react-redux-starter-kit.git', {silent: true});`
 `clearInterval(interval);`

If I run a git pull of the repo, outside of the cli, its pulls properly.

Here is my terminal output.

`redux new testRedux`
`create: project directory created`
`create: setting up tracking with git...`
`error: Something went wrong... please try again.  Make sure you have internet access`
`error: Error code: 128`

I'm running El Capitan
git version 2.5.4 (Apple Git-61)
Node v5.3.0

**Comment by d0nkeyBOB** [comment]
Can confirm cloning of source, rebuilding and running, per contributor directions, works on both 5.1.0 and 5.3.0.

**Comment by SpencerCDixon** [comment]
> Can confirm cloning of source, rebuilding and running, per contributor directions, works on both 5.1.0 and 5.3.0.

are you saying it's working now?  I'm confused.

Just to confirm, are you able to clone down the repo using the `https` link and not the `git` link?  Because error 128 might have to do with an SSH error: [see here](http://stackoverflow.com/questions/17244703/what-is-error-code-128)

**Comment by d0nkeyBOB** [comment]
I was able to pull the react-redux-starter-kit repo by 'git init' then 'git pull' in following your code execution. This was outside of the redux-cli. I could also clone react-redux-starter-kit without problems.

To getting a working CLI, I cloned your source, built it, then 'npm link'. The cli worked properly after that.

**Comment by SpencerCDixon** [comment]
Interesting, thanks for the heads up, going to look into it!

**Comment by SpencerCDixon** [comment]
@d0nkeyBOB V1.1.4 should have fixed this issue.  I switched from using the https git URI to using the git one.  If you could reinstall and confirm everything is working on your end without having to the linking shennanigans I would appreciate it :)

**Comment by SpencerCDixon** [comment]
Nvm don't think its working still. Going to keep investigating
