### ISSUE TITLE
Send CLI usage analytics in order to improve the CLI (take inspiration from ember-cli) 

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/redux-cli#28]
package: https://www.npmjs.com/package/leek
codeStorage: https://github.com/ember-cli/ember-cli/blob/master/package.json#L6
https://github.com/ember-cli/ember-cli/blob/master/lib/cli/index.js#L86

**Comment by anithri** [comment]
I understand the advantages of this, but it still makes me a bit uneasy.  We'd have to allow people to opt out, and be very thorough on how errors are caught.  

I'm also concerned about how much data we would gain from this.

**Comment by SpencerCDixon** [comment]
Yeah not used enough to be worth it.. I'd say just close
