### ISSUE TITLE
Deprecate .reduxrc in favor a .redux-cli file.

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/redux-cli#29]
look into using Yam: https://www.npmjs.com/package/yam potentially

**Comment by xml** [comment]
Definitely shouldn't have a file that could be confused - because of its name - for being related to redux itself...

**Comment by anithri** [comment]
I think the name of the rc file needs to match the name of the command.  and I think that changing the name of the command to `redux-cli` while accurate, is not needed.  If we don't want `.reduxrc` then we should look at renaming the whole project as #46

**Comment by anithri** [comment]
Renaming the project to blueprint-cli, results in a `.blueprintrc`. I feel this addresses the major concerns.
