### ISSUE TITLE
Redux CLI exits with error

### ISSUE THREAD

**Issue by nmrony** [SpencerCDixon/redux-cli#39]
I installed `redux-cli` as per instruction like below
```sh
npm i -g redux-cli
```
and using node installed with `nvm`. When I run `redux g dumb HelloWorld`, redux-cli is throwing error
```sh
/usr/bin/env: node --harmony: No such file or directory
```
How to use it with `node` installed by `NVM`? I can symlink `node` to path where cli is looking for but looks like dirty hack to me.

**Comment by SpencerCDixon** [comment]
Are you sure you're using nvm and not system node?  I would `nvm ls` to confirm.  

Try doing this:
```
nvm install 5.1
nvm use 5.1
npm i redux-cli g
redux new <app name>
```
If that doesn't work lemme know

**Comment by nmrony** [comment]
@SpencerCDixon Yes, I am sure. My `nvm ls` output is like below
```sh
       v0.10.40
->       v5.7.0
node -> stable (-> v5.7.0) (default)
stable -> 5.7 (-> v5.7.0) (default)
iojs -> iojs- (-> N/A) (default)
```
Even after installing `redux-cli` as global, I am getting following error
```sh
redux new redux-cli-test
/usr/bin/env: node --harmony: No such file or directory

```

**Comment by SpencerCDixon** [comment]
Having a hard time trying to find a good fix (I also don't have ubuntu which I could test things with) [I found this issue that might be of some help](https://github.com/nodejs/node-v0.x-archive/issues/3911) try running `ln -s /usr/bin/nodejs /usr/bin/node` and see if that fixes the issue

**Comment by alienspaces** [comment]
On Ubuntu.

Changing all executables to call node directly (instead of through env)
```
#!/usr/bin/node --harmony
require('../lib/cli');
```

See https://bbs.archlinux.org/viewtopic.php?id=168479

**Comment by nmrony** [comment]
@SpencerCDixon I can symlink as I mentioned. but this does not solving the problem. Because I need to use different `node` version for different project. I can send you a `PR` but first I need to study your codes. Also are there any rules of contributions?

**Comment by SpencerCDixon** [comment]
Feel free to submit a PR that will fix it for Ubuntu users.  I don't personally have Ubuntu set up or a way to test it, sorry :/

**Comment by nmrony** [comment]
@SpencerCDixon I found a workaround while using various `NodeJS` using `NVM`. I set `NodeJS` stable version as `default` version to load by NVM while a new terminal window is opened as follows.
```sh
nvm alias default node
``` 
Then install `redux-cli` globally and it is working fine. BTW awesome work :+1:  Closing this issue as seems resolved
