### ISSUE TITLE
Generate redux module file in lowercase

### ISSUE THREAD

**Issue by nicolasiensen** [SpencerCDixon/redux-cli#41]
Hey guys,

First of all, congrats for this awesome tool, it's been very helpful to bootstrap a new project.

I was using the duck generator and I realized that the file name is being generated in camel case, isn't it the case of these files to be generated in sneak case? If you agree with that I can submit a pull request ;)

Cheers!

**Comment by SpencerCDixon** [comment]
Hey @nicolasiensen I would be fine with having the default for ducks be snake case.  The blueprints are designed in a way that you can override them though for your own project specific use case, but I agree snake_case is probably more universally accepted
