### ISSUE TITLE
cli arguments aren't passed into options.entity.options

### ISSUE THREAD

**Issue by nathanielks** [SpencerCDixon/redux-cli#43]
Happy Friday!

I've created a blueprint and am trying to add some template variables, but unfortunately any cli arguments I pass aren't being processed, even `--debug`. Here's a [gist](https://gist.github.com/nathanielks/3a5f272a494e0dafff9a) with the files. I'm `console.log`ing the entity so you can see the results.

**Comment by nathanielks** [comment]
Diving in here more, I see [nothing is actually passed](https://github.com/SpencerCDixon/redux-cli/blob/master/src/cli/redux-generate.js#L22) into options.entity.options and `commander` doesn't seem to have support for additional arguments when they're not defined =\

**Comment by nathanielks** [comment]
I haven't worked with `commander` before, but I'm wondering if `blueprint/{name}/index.js` could define additional arguments to be parsed and then loaded in the [`commander.action`](https://github.com/SpencerCDixon/redux-cli/blob/master/src/cli/redux-generate.js#L16) step?

**Comment by SpencerCDixon** [comment]
Yeah haha somewhat annoying, I looked into commander source a couple days ago and think I have a solution.  Will put together a pr this weekend and let you know when it's ready.

**Comment by SpencerCDixon** [comment]
@nathanielks [pr to fix issue](https://github.com/SpencerCDixon/redux-cli/pull/44/files) .  Should have access to everything you need in blueprints now!
