### ISSUE TITLE
Make adding tests optional

### ISSUE THREAD

**Issue by ericwooley** [SpencerCDixon/redux-cli#45]
Not every module I make is going to need a unit test file (sometimes you have a deadline and need to push something out, or whatever).

It would be great to have a shortcut to skip the test generation. EG: 
`redux g -nt dumb SimpleButton # shorthand`
`redux g --no-toest dumb SimpleButton #full`

I agree with the ideal of 100% unit test coverage, but it's not always practical.

**Comment by SpencerCDixon** [comment]
You could split the blueprint into two as well.  Ie have a `redux g dumb SimpleButton` and a `redux g dumb-test SimpleButton` for when you want a test generated

**Comment by ericwooley** [comment]
@SpencerCDixon  Ah nice, I didn't see you had implemented the blue print stuff already! nice work!

I need to checkout the new way of doing things.

**Comment by SpencerCDixon** [comment]
:+1: lemme know if you have any questions!

**Comment by ericwooley** [comment]
This seems pretty awesome! Your solution seems acceptable to me, but has the potential for needing to keep files in sync. 

Closing the issue, I guess reopen if you want to add the option.
