### ISSUE TITLE
Option to create test within component folder

### ISSUE THREAD

**Issue by ro-savage** [SpencerCDixon/redux-cli#47]
Awesome work on this. Looking forward to putting it to some good use!

It would be great if there was an option to have the automatic tests created in the same folder as the component/container/form/duck rather than in a test directory.

I am unsure if this can be done with blueprints? Or if it will need to be written in as part of the commands?

**Comment by SpencerCDixon** [comment]
Yeah this can definitely be done with blueprints.  You have a couple options:

1.  You can make a blueprints folder in your own project that just has the test file in the same directory so when the generator generates both files will be there. 

2.  You could submit a pr that adjusts the logic on the current blueprints to accept a flag and if the flag is present it moves the test blueprints to a different location (although possible this might be more difficult to do)

**Comment by ro-savage** [comment]
Thanks for the quick response :)

I'll investigate the blueprint option for now. And if/when I get a chance take a look at the flag option and submitting a PR.
