### ISSUE TITLE
redux new foo - cannot clone react-redux-starter-kit

### ISSUE THREAD

**Issue by hetii** [SpencerCDixon/redux-cli#48]
When call redux new foo
its hang on:
loading: Fetching git@github.com:davezuko/react-redux-starter-kit.git from github. 

Looks like it try establish first ssh session instead https.

**Comment by SpencerCDixon** [comment]
yeah it does, make sure to have ssh with github setup on your machine

**Comment by hetii** [comment]
But why I should use ssh setup when by using https I don`t need to to anything else to grab this project ?
By changing lib/sub-commands/new.js to:
  _this2.gitPullTask.run('https://github.com/davezuko/react-redux-starter-kit.git').then(function () 
I was able  to start new project.

Btw maybe there should be some additional wrapper and if getting project over ssh fails (cause of timeout) then try it get by https ?

**Comment by gvlatko** [comment]
Not working for me either, and i have ssh with github

**Comment by SpencerCDixon** [comment]
That would be nice to have the fallback, https was giving other people issues ha.  Open to a PR if you wanna make the fallback

**Comment by enyachoke** [comment]
Am thinking of maybe introducing a https switch something like ```--use-https```

**Comment by SpencerCDixon** [comment]
go for it! I'm open to a PR for sure

**Comment by timothyallan** [comment]
Ahhh, that's why I'm seeing:
```
loading: Fetching git@github.com:davezuko/react-redux-starter-kit.git from github. ⠴
The authenticity of host 'github.com (192.30.252.130)' can't be established.
```
Thanks for the pending fallback :)

**Comment by enyachoke** [comment]
That is how ssh works basically you have to tell you machine to trust github.com. @timothyallan  checkout https://help.github.com/articles/set-up-git/ for how to configure ssh or pull my branch.
