### ISSUE TITLE
Cannot find module 'eslint-config-standard-jsx' from ...

### ISSUE THREAD

**Issue by hetii** [SpencerCDixon/redux-cli#49]
When use this project to generate new redux environment after npm run start I get:

Module build failed: Error: Cannot find module 'eslint-config-standard-jsx' from '.... /node_modules'

**Comment by SpencerCDixon** [comment]
Might have something to do with the react-redux starter kit changing.  Did you try `npm i eslint-cnofig-standard-jsx -D`?

**Comment by hetii** [comment]
yep, when I install it all seams to work,
