### ISSUE TITLE
Allow form generator to take a fields option which will prepopulate the form with those fields

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/redux-cli#5]

**Comment by jflayhart** [comment]
Interesting... so how would this work, like: `redux g form firstName lastName email password`? Would this only be for the field names or how would it know that the field type should be of attribute "email" or "password" or "text"?

**Comment by SpencerCDixon** [comment]
Yeah something along those lines would be nice.  Maybe you would separte field names with their types like in a rails migration.

firstName:text email:email lastName:text age:number    etc.

**Comment by jflayhart** [comment]
Ok, seems pretty straight forward then; so a complete command for this would include an optional `--fields` flag with any number of `<field name>:<input type>` arguments. In theory, this could look like:

`redux g form <form name> --fields=<field name>:<input type>` where multiple fields are separated by spaces. Unless there's a cleaner way...

**Comment by SpencerCDixon** [comment]
Yeah I totally agree with the overwrite issues.  If you want to try and tackle that I'd be open to a PR. I just started a new job though and need to learn Go and Angular at the moment so not sure how much free time I'll have to work on that for at least a few weeks.

**Comment by jflayhart** [comment]
Cool, same here :) I just wanted to create some ideas here for reference whenever I might have time to work on this...

Another idea, however, is to allow another flag for `--validation=true` or something, which would create some simple validation logic around the user-defined fields during the generation process. That would be pretty cool... I would love to work on this when I have time, which isn't now unfortunately. But will leave these notes behind for future reference.

**Comment by anithri** [comment]
#110 will address this. And this issue will be closed when it is accepted

data will be able to be passed to blueprints that can use to do things like generate form fields for each attribute.

**Comment by anithri** [comment]
Merged #110 into the 2.0 master.
