### ISSUE TITLE
Using namespaces in files names

### ISSUE THREAD

**Issue by anatoliyarkhipov** [SpencerCDixon/redux-cli#55]
Hi! Our team is actively using namespaces in projects and when I'm trying to define the name of generated file like this:

```bash
redux g dumb Foo/Bar
```

the CLI generates this:

```bash
  create: /home/vagrant/Code/todo/src/components/Foo/Bar/Foo/Bar.js
  create: /home/vagrant/Code/todo/tests/components/Foo/Bar.spec.js
```

`Foo/Bar` is doubled in the file name, but not in the test.

You can reproduce it on the fresh installation of this boilerplate:
https://github.com/davezuko/react-redux-starter-kit

My version of `redux-cli` is 1.4.2. 

Am I doing something wrong or it's just not supported yet?

**Comment by SpencerCDixon** [comment]
It has to do with how the blueprints are set up.  I would take a look at this section of the [readme](https://github.com/SpencerCDixon/redux-cli#file-tokens) and also take a look at the blueprints that are in your project (i'm guessing you're using the ones that come with react-redux starter kit) and see if that helps solve your issue
