### ISSUE TITLE
Use the new-project branch of react-redux-starter-kit

### ISSUE THREAD

**Issue by MrOutis** [SpencerCDixon/redux-cli#56]
There's a branch of the starter-kit without the example app:
https://github.com/davezuko/react-redux-starter-kit/tree/new-project

It would be nice if `redux init` uses that instead.

**Comment by emzero** [comment]
+1

**Comment by MrOutis** [comment]
Or do this manually:
```
git fetch origin new-project                      # Make sure you've fetched the latest copy of this branch from remote
git checkout new-project                          # Checkout the new-project branch
m -rf .git && git init                            # Start a new git repository
```

**Comment by SpencerCDixon** [comment]
Yeah definitely need to get version tied down, going to do that for the new fractal file structure
