### ISSUE TITLE
'new projectName' never finishes fetching react-redux-starter-kit

### ISSUE THREAD

**Issue by xml** [SpencerCDixon/redux-cli#58]
I've been operating under the assumption this is some dumb local environment issue, and it probably still is, but it's got me baffled. 

Using redux-cli@1.4.2, on node 5.7.0 on Mac OS. I re-installed redux-cli multiple times and have no trouble with that. But if I try to scaffold a project with it, the install runs forever, with no errors and no timeout. At the moment, it has been a half hour, with no progress. I was playing with it before a three-day business trip, and when I came back from that trip and opened the terminal window again, the same fetch was still going, even though it had been on-line and off-line dozens of times since then. 

It eternally sticks on: 
    `loading: Fetching git@github.com:davezuko/react-redux-starter-kit.git from github.`

I can download that repo by itself with no trouble: either a zip download or a clone completes successfully, and almost immediately.

Here's a full capture of the current terminal:

![voila_capture 2016-03-24_13-05-19_](https://cloud.githubusercontent.com/assets/1126175/14008895/506f9aba-f1c1-11e5-8690-9e42cfdf64be.png)

**Comment by sergey-stukov** [comment]
Have the same issue, after some digging have a success with following command.
`redux new -H demoReduxCli`

**Comment by SpencerCDixon** [comment]
It defaults to use ssh for github so if you don't have ssh set up it will bork.  Passing the -H flag will make it use https instead.  Starting to think we should swap to have https be the default haha.  I'll add the -H flag to the readme

**Comment by simonlinj** [comment]
same issue here... Why isn't HTTP the default one, if there is no difference in between? Since not everyone has github ssh configured. thanks!

**Comment by SpencerCDixon** [comment]
Yeah I'll switch it in the morning.  Earlier in development https wasn't working for someone but when using ssh it worked but it was honestly probably completely unrelated issue.  I'll close this once I make the switch in the AM
