### ISSUE TITLE
IDE friendly

### ISSUE THREAD

**Issue by simonlinj** [SpencerCDixon/redux-cli#60]
Is there a way to make the blueprint's files IDE friendly? Currently I'm using Webstrom, and see error warning everywhere.

**Comment by SpencerCDixon** [comment]
I don't use Webstorm so not really sure what to tell you.  It looks like you can ignore [files/folder though.](https://www.jetbrains.com/help/webstorm/2016.1/ignore-unversioned-files.html?origin=old_help)
