### ISSUE TITLE
Make BrowserSync a core dependency

### ISSUE THREAD

**Issue by gabeweaver** [SpencerCDixon/redux-cli#63]
**This is indirectly related to the CLI but equally important since it is using [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit). I'll take this up there but wanted to get input here as well. 

Why?
Because **everyone** should be testing across multiple devices and browsers while building their apps.

What?
Make [BrowserSync](https://www.browsersync.io/) a core dependency and integrate it into the server. 

Opinionated things I'd love to get feedback on:

1. Is this something that other feel would be valuable? If so, I'd like feedback so I can open a PR and contribute back as I work on integrating BrowserSync into my local project. 
2. Should this be super opinionated and included as the default? (I would argue Yes because it doesn't actually change or alter the current behavior in any way. Rather, it provides an enhancement running on different, configurable port.) 
3. Should we be building, merging, and deploying things without properly testing them across many devices and browsers? No.
4. Does BrowserSync make it easier, more efficient, and more enjoyable to do #3. Yes. 
5. If we want to expose [config options for BrowserSync](https://www.browsersync.io/docs/options/) (which i think we should), where would be the ideal place for them?

**Comment by SpencerCDixon** [comment]
Not really sure if this would be the right place for the discussion... Don't see how browsersync integration affects the CLI.  If you wanted to make a blueprint that helps with using browsersync I'm open to including that in the default set of blueprints.  Closing for now though
