### ISSUE TITLE
What is the best way to group functionality using redux-cli

### ISSUE THREAD

**Issue by iroy2000** [SpencerCDixon/redux-cli#70]
I love this tool,  but I was wondering how do you group things together using redux-cli

For example, if a component is page specific ( in my case, index.jsx is the container )

![screen shot 2016-05-03 at 9 46 46 am](https://cloud.githubusercontent.com/assets/487520/14991048/7b1ddd4a-1114-11e6-9ebf-36362564a900.png)

So wonder if I can generate structure like

components/home/
components/school/
components/school/list/
components/school/detail

If not, do you think something like the following would help ?

`redux g dump SubmitSchoolButton --f school/list`

**Comment by iroy2000** [comment]
Just found out it did support this functionality :)

Nice!!

**Comment by SpencerCDixon** [comment]
So the file structure in the blueprint will get re-created when you use the generators.  If you want to you can create a custom 'blueprints' folder in your project and make a blueprint that generates to your needs.

Certain 'tokens' can be replaced in the generation process.  [See this section of the readme for more info](https://github.com/SpencerCDixon/redux-cli#file-tokens).  You can also create custom tokens inside the index.js of a blueprint if you want new tokens.

Example use case:  I'm working on a UI kit at work and I created a generator that generates this file structure:

```
redux g comp CardContent

1 src/components/CardContent
2 ├── CardContent.example.js
3 ├── CardContent.js
4 ├── CardContent.less
5 ├── CardContent.test.js
6 └── index.js
```

So you should be able to customize/extend either the existing generators or make a custom one that lets any level of nesting you want.  In my UI kit generator I also have an `afterInstall` hook that adds the import statements in necessary places for distributing the components

**Comment by SpencerCDixon** [comment]
haha okay great!

**Comment by iroy2000** [comment]
So do I need to copy the whole structure here to overwrite the configuration ?

https://github.com/SpencerCDixon/redux-cli/tree/master/blueprints

And you mentioned you are working on the `UI kit at work`, are you able to share that ?  Because this is the structure that we were using now.

**Comment by SpencerCDixon** [comment]
Yeah so you can create a `blueprints` folder in your project then the name of the folders inside there will be available blueprints you can generate.  I can't give you link to repo but here is more info incase it helps:

File Structure:
```
   1 blueprints
      2 └── comp
      3     ├── files
      4     │   └── __root__
      5     │       └── components
      6     │           └── __name__
      7     │               ├── __name__.example.js
      8     │               ├── __name__.js
      9     │               ├── __name__.less
     10     │               ├── __name__.test.js
     11     │               └── index.js
     12     └── index.js
     13
     14 5 directories, 6 files
```

Index.js:
```
const fs = require('fs');
const path = require('path');

module.exports = {
  description() {
    return 'Generates a UI component template';
  },
  afterInstall(options) {
    const name = options.entity.name;
    const srcIndexPath = path.resolve(__dirname, '..', '..', 'src', 'index.js');
    const exportString = `export { ${name} } from './components/${name}';`;

    fs.appendFile(srcIndexPath, exportString, function(err) {
      if (err) {
        console.log(err);
        console.log('ERROR: wasnt able to append component in index exports');
      }
    });

    console.log('SUCCESS: added your component to src/index.js');
  },
};
```

**Comment by iroy2000** [comment]
Thanks that helps a lot \o/

**Comment by iroy2000** [comment]
Now I have another issue related to that

I want to created a 

`redux g comp test --folder hello`

Where I want the --folder options to replace to __name__

So instead of the following

![screen shot 2016-05-03 at 2 11 18 pm](https://cloud.githubusercontent.com/assets/487520/14998499/f5289624-1138-11e6-85fc-763078b71c1b.png)

I want to put the `artifacts` into the hello folder that we have. 

What do I need to do ?

**Comment by SpencerCDixon** [comment]
you could create a custom token maybe named `__folder__` that gets replaced with whatever you pass into that flag.  

In the `index.js` of your blueprint do something like this:
```
... rest of file
  fileMapTokens: function(options) (
    // Return custom tokens to be replaced in your files
    return {
      __folder__: function(options){
        return options.entity.options.folder;
      }
    }
  },
... rest of file
```

Then the `__folder__` token can be used in your file structure and the flag will replace it.  You might want to have some conditional logic there for if the flag is not passed what should that value be replaced with.  Or maybe prompt the user for folder name if they forgot to include it in the flag.  Just some thoughts...

**Comment by iroy2000** [comment]
Nice, thanks, that solved my problem.  Thanks for the quick response.  Closing it now ~
