### ISSUE TITLE
generator should support --path option

### ISSUE THREAD

**Issue by heygrady** [SpencerCDixon/redux-cli#72]
It is common to create apps in react-redux using the [fractal project structure](https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure) outlined in the manual. Currently a generator can be used to easily create a component in the main project folder, but you can't use it to create a component inside of a route. Using [ember-cli](http://ember-cli.com/user-guide/#using-pods) you can use the `--path <path>` option with some generators to create the files in a subfolder.

In redux-cli it might look like this:

``` bash
redux g dumb butter --path routes/about
# creates a component in src/routes/about/components/Butter/
# creates a spec file in tests/routes/about/components/Butter/
```

One of the best reasons to use a generator is that it automatically creates the test files for you. Having to manually create the test files when creating a component within a route is an example of why people often prefer to use a generator.

The proposal here is that if someone wants to prefix the thing they generate with a path that should be easy to do. I personally think it should apply to any blueprint.

_Note:_ I might build this feature soon.

**Comment by SpencerCDixon** [comment]
Would definitely be open to a PR, this sounds like a great feature!

**Comment by xml** [comment]
Note a related issue: if you try to run `redux g` from anywhere other than the project root, it fails _and creates a new `.reduxrc` in that folder`, but with no values in it._ Ideally, it would simply look upward first for a `.reduxrc` in a parent directory, and then determine the paths from there. That feels maybe tightly coupled enough with the option to specify a `--path` that it would need to be fixed first/together?

**Comment by xml** [comment]
Further, related to #75, if you try to run a generator from inside of a blueprint folder, and thus accidentally create a `.reduxrc` in there, the next time you run the generator, it'll try to copy that `.reduxrc` to the newly-scaffolded module...

**Comment by heygrady** [comment]
@SpencerCDixon I didn't see any tests related to installing a blueprint. I added the option in my fork and it works as expected. I should send a pull request?

```
$ redux g dumb button --path routes/Todo
  info: installing blueprint...
  create: /project/src/routes/Todo/components/Button.js
  create: /project/tests/routes/Todo/components/Button.test.js
  info: finished installing blueprint.
```

**Comment by ericwooley** [comment]
In addition to the path option, we could use the current location, and search up the directory tree for a blueprint, and install it where we currently are.

**Comment by senta** [comment]
I want this feature too! for now, I can achieve that with customize "tokens" and "locals" instead change redux-cli core.

My blueprints/route/index.js look like below.

```
var humps = require('humps');

function normalize (name) {
  return name.match(/([^\/]+)$/)[1];
}

module.exports = {
  locals: function(options) {
    // Return custom template variables here.
    var name = normalize(options.entity.name);

    return {
      pascalEntityName: humps.pascalize(name),
      camelEntityName: humps.camelize(name),
      snakeEntityName: humps.depascalize(humps.pascalize(name)),
      dashesEntityName: humps.depascalize(name, { separator: '-' })
    }
  },

  fileMapTokens: function(options) {
    // Return custom tokens to be replaced in your files
    var name = normalize(options.entity.name);

    return {
      __name__: function(options){
        // logic to determine value goes here
        return humps.pascalize(name);
      },
      __dirname__: function (options) {
        return options.entity.name.split('/').map(humps.pascalize).join('/');
      }
    }
  }
}
```

**Comment by prescottprue** [comment]
+1 this would be a nice feature. @senta your solution works nice for now.

**Comment by awhillas** [comment]
Can't you simply add the `--path` or whatever param you like to the path in the index.js file as you get all the command line params there...?

**Comment by awhillas** [comment]
Can't you just take the/a `--path` option in the index.js's `local:` param, similar to what @senta did above and do what you like with it there as you get all the command line params?

**Comment by anithri** [comment]
#110 will help with this, discussion on particulars at #112
