### ISSUE TITLE
Run redux g dumb SimpleButton error on Windows

### ISSUE THREAD

**Issue by bodyno** [SpencerCDixon/redux-cli#73]
![4d7h5uzxw cni4 ky1riowy](https://cloud.githubusercontent.com/assets/5443058/15239404/e1fe4b46-1914-11e6-93d0-d8ab83811502.png)
There is the picture

**Comment by mzvast** [comment]
`redux g duck todos
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\redux-cli\bin\redux-g'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

**Me either,and there is no redux-g file inside `node_modules\redux-cli\bin` **

**Comment by bodyno** [comment]
Ok. I see.
Thanks a lot.
