### ISSUE TITLE
Generators generating *.test.js files instead of *.spec.js files?

### ISSUE THREAD

**Issue by kenjim83** [SpencerCDixon/redux-cli#84]
First off thanks for creating this awesome tool! 

I noticed when using the generator all the test files created are all *.test.js file but the test runner only looks for *.spec.js files.

**Comment by anithri** [comment]
This is a mismatch of the built in blueprints and the [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit)

I think the plan should be to have specific sets of blueprints to go with the default starter kits.

**Comment by anithri** [comment]
Something to address.  related discussion at #114

**Comment by anithri** [comment]
Closing this for inaction.
