### ISSUE TITLE
update docs for how to customise redux-duck paths

### ISSUE THREAD

**Issue by nicolanicola** [SpencerCDixon/redux-cli#88]
When I create a duck, the files are created in <sourceBase>/redux/modules/ and <testBase>redux/modules/.  Suggest there should be a <reducersBase> and a <reducersTestBase>

**Comment by SpencerCDixon** [comment]
> Suggest there should be a and a

Sorry I don't follow

**Comment by anithri** [comment]
The default Duck blueprint places the files in `__root__/__duck__/__name__.js` and the test files in `__root__/redux/modules/__name__.test.js`

**Comment by anithri** [comment]
Something to address. related discussion at #114

**Comment by anithri** [comment]
We're adding better config options for paths.  

I'm closing this for inaction on the part of the submitter.  Happy to address it again if necessary after 2.0 is done.
