### ISSUE TITLE
Error: Cannot find module '../lib/cli' (on MacOS)

### ISSUE THREAD

**Issue by jkurei** [SpencerCDixon/redux-cli#89]
I was gonna try redux-cli, but I can't get past this and I don't know how to troubleshoot it. This is what I'm getting: 

`{ Desktop } > redux new rc-test
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jesusiniesta/.npm-packages/lib/node_modules/redux-cli/bin/redux.js:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)`

I'm on MacOS, using npm 3.10.8 and node 4.3.1. I've reinstalled npm, but it wasn't it. I couldn't replicate this in an Ubuntu system, which made me suspect it's something weird on my machine, but other global modules are working just fine.

**Comment by mariotacke** [comment]
Running into the same thing right now. Latest redux-cli.

**Comment by anithri** [comment]
Not happening on Ubuntu, I have no access to MacOS.

Could someone olease confirm if this is still the case today?

And any insight on why this might be happening would also be appreciated.

**Comment by SpencerCDixon** [comment]
Should maybe remove the 'new' command actually or have it go to `create-react-app` instead of the starter kit

**Comment by jamesr73** [comment]
Working for me on MacOS Sierra (10.12.6).

I'm managing Node installs with nvm. Tested with:
node v4.3.1 + npm v2.14.12 (default)
node v4.3.1 + npm v3.10.8 (as originally reported)
node v6.11.3 + npm v3.10.10

**Comment by jamesr73** [comment]
+1 for new => create-react-app

**Comment by anithri** [comment]
moving conversation about new, starter kit, create-react-app etc to #105 

@jkurei are you still having this problem or could you confirm you aren't?

**Comment by anithri** [comment]
One way that error can happen is to execute the cli in such a way that it doesn't think it's in the directory it's supposed to be in.  `bin/bp` expects to find the cli code at `../lib/cli`.  

This probably is a problem with how npm installed the package.

**Comment by anithri** [comment]
With a complete rewrite of the CLI, I think this bug or misconfiguration is a relic of history now, and such I'm closing this.

Please feel free if you have the problem after the 2.0 release.
