### ISSUE TITLE
Unclear/Uncaught error if generator called without a name argument 

### ISSUE THREAD

**Issue by xml** [SpencerCDixon/redux-cli#96]
If I call `redux g container SomeName`, everything's fine. 

If I call `redux g container`, instead of an intelligible error that tells me I always need to supply a name argument, I get an uncaught error:
```
/node_modules/humps/humps.js:53
    string = string.replace(/[\-_\s]+(.)?/g, function(match, chr) {
                   ^

TypeError: Cannot read property 'replace' of undefined 
```

**Comment by anithri** [comment]
@jamesr73 does #110 solve this?  I'm on the wrong machine to test that right now.

**Comment by anithri** [comment]
CLI exits clean with a help message after #110
