### ISSUE TITLE
Missing instructions on contributions

### ISSUE THREAD

**Issue by anithri** [SpencerCDixon/redux-cli#98]
I haven't found any statements about how @SpencerCDixon views external contributions.

I am a great admirer of the simplicity of this tool and how easy it is to create and customize blueprints.  It holds a place in my tool chain.  My thanks and respect to Spencer for it.  I'm looking for your guidance before I do something to make sure development continues and improves.

This project isn't updated very often, there are pull requests languishing and if Spencer has talked about  his intentions, I can't find it.  I'm fine with forking and creating a personal version, but I suspect that others have the same pain points that I do, so some guidance for your wishes for the future is requested.  Do you want to maintain as BDFL, and update more frequently.  Or add others that have permissions to approve pull requests and push new versions.  Would you change ownership of the repo and npm package to a different maintainer that meets your standards?  Do you not care and the wish to have someone else figure it out?

I just want the project to move again, and I don't want to step on any toes while making that happen.  If someone else wants to take the lead I'm ok with that too.

My needs are mostly around blueprint directory configuration.  I'd like to use ~/.blueprints or ~/.local/.blueprints as a common directory.  I'd like to be able to use npm to package and share blueprints.  I'd like to be able to clone blueprints into the local directory to encourage customization.  I'd like to have a solution to sub-components.  I'd like to expand the available blueprints.  I'd like to bounce ideas about how i've been organizing components with others.  

*edited for stronger good will indications*

**Comment by SpencerCDixon** [comment]
Hey @anithri yeah I honestly just got kind of burned out and don't really want to do much more work on the project.  Would you be interested in becoming a maintainer of the project?

**Comment by SpencerCDixon** [comment]
We could pin 1.9 and if you want to continue work/manage PR's/issues you could do it under a 2.0 release?  Let me know your thoughts.  I do appreciate your detailed feedback and being kind :-)

**Comment by anithri** [comment]
This sounds good to me.  I'm happy to take that on.

I've looked through the PR's, I'll look at the Issues next.

**Comment by anithri** [comment]
My Idea's for 2.0

Take the foundation laid by 1.0 and extend the capabilities.

Blueprints are most useful when able to be shared, copied and customized.
The Blueprints directory discovery will be expanded to include home directories, ENV defined directories, npm packages, config file defined. A single directory may be defined as the default directory for blueprint generation. Provide a way to copy blueprints into the default directory in order to increase the ease of customizing your own version of a default or shared blueprint.

Enhance the .reduxrc experience. Add the ability to have home directory and ENV var defined locations. Allow merging of multiple .reduxrc files.  **note** I've already implemented this using [rc(npm)](https://www.npmjs.com/package/rc)

.reduxrc should be able to set blueprint directory locations.  Look at adding ability to set options here as well.

Enhance the Generator experience. Look to Ruby on Rails for inspiration.
Look for ways to enable generator composition. Look for ways to insert code into existing files. Find ways to share and use partials in generators.  Find ways to publish blueprints via npm.

Define a generator to create a npm package dir ready to share blueprints with the community.

**Comment by SpencerCDixon** [comment]
Cool that all sounds great to me!  I'll get you added to the repo :-)

**Comment by anithri** [comment]
Are there uncommitted changes somewhere?  NPM has 1.9, but the repo is at 1.8

**Comment by SpencerCDixon** [comment]
let me check locally

**Comment by SpencerCDixon** [comment]
Doesn't look like any new changes.  Can't remember what I did it was a long time ago but should be good to change things!
